# Generated by Django 2.0.2 on 2018-03-07 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180307_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('bucket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Bucketlist')),
            ],
        ),
    ]
